server:
  port: 8082
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/product-service
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 32
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 15s
      password:
  cache:
    type: redis
    redis:
      time-to-live: 2m
      cache-null-values: false
#logging:
#  level:
#    ROOT: DEBUG
#    org.hibernate.SQL: DEBUG
#    com.personal.project.productservice: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
